services:
  api:
    image: node:jod-alpine3.21
    command: sh -c 'cd /app && npm i && node --watch --import tsx src/index.ts'
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_NAME: dockerize_it
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: dockerize@it
      DATABASE_SYNCHRONIZE: true
    depends_on:
      - database
  database:
    image: mysql:9.2
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dockerize_it
      MYSQL_ROOT_PASSWORD: dockerize@it
